name: Update copyright year(s) in license file

on:
  schedule:
    - cron: '0 8 1 1 *' # 00:00 AM (UTC+8) on January 1
  push:
    branches:
      - main

jobs:
  update-license-year:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: FantasticFiasco/action-update-license-year@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
