name: pre-commit

on:
  pull_request:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: shellcheck shfmt
          version: 1.0
      - uses: supplypike/setup-bin@v3
        with:
          uri: "https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64"
          name: "hadolint"
          version: "v2.12.0"
      - uses: pre-commit/action@v3.0.0
